### ISSUE TITLE
Feature: convar to allow spectating only friendly team

### ISSUE THREAD

**Issue by L1ghtman2k** [RomeoCantCode/Northstar-Spectator-Mod#1]
Usecase is really just for competitive LTS/CTF pugs, since in-game spectator [mode is broke](https://github.com/R2Northstar/NorthstarMods/issues/501)

**Comment by faky1337** [comment]
@L1ghtman2k 
#2 
Added the convar and check, didnt test so far. might be able to test it next week.
In theory you can change the convar on the fly.
